seed: 0


cron:
  username: "federico"
  python_path: "/opt/anaconda3/bin/"
  clean: True
  stop: False
  py_cmds:
    scheduler:
      minute:
        every: 60
    retrieve_data:
      minute:
        every: 10
    train:
      hour:
        every: 2
      dow:
        "on": "MON"

      

data:
  path: "data/ESC-50"
  sample_rate: 8000
  train_folds: [1,2,3]
  val_folds: [4]
  test_folds: [5]
  batch_size: 8
  retrieval_size: 50

model:
  base_filters: 32
  n_classes: 50
  optimizer:
    lr: 3e-4

trainer:
  gpus: 0 #1
  max_epochs: 10

defaults:
- hydra/job_logging: colorlog
- hydra/hydra_logging: colorlog